#!/bin/sh
echo "***********************************"
echo "*          CoverCockpit           *"
echo "*               by                *"
echo "*          dream-alpha            *"
echo "***********************************"
echo ""
echo "CoverCockpit plugin installed successfully."
echo "Please restart DreamOS now!"
echo ""
exit 0
